export const FEATURE_FLAG_KEYS = [
  "AUTO_HIDE_REPORTS",
  "VIDEO_FEED",
  "SHADOW_BAN",
  "OTP_REQUIRED",
  "LISTING_MODERATION_ENABLED",
  "CHAT_ENABLED",
  "TRUST_SCORE_ENFORCEMENT",
  "REPORTING_ENABLED",
  "COMMAND_PALETTE",
  "RELIST_ENABLED",
  "SAVED_SYNC",
  "RECENT_SYNC",
  "SELLER_ANALYTICS",
  "SEMANTIC_SEARCH",
  "AI_COPILOT",
  "AI_FRAUD_RISK",
  "AI_CHAT_COPILOT",
  "RECOMMENDATIONS_FEED",
  "PRICE_INTELLIGENCE",
  "FORECAST_ANALYTICS",
  "AB_EXPERIMENTS"
] as const;

export type FeatureFlagKey = (typeof FEATURE_FLAG_KEYS)[number];
