export const pakistanCities = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Hyderabad",
  "Gujranwala",
  "Sialkot",
  "Sargodha",
  "Bahawalpur",
  "Sukkur",
  "Larkana",
  "Mardan",
  "Abbottabad",
  "Mingora",
  "Dera Ghazi Khan",
  "Rahim Yar Khan",
  "Kasur",
  "Okara",
  "Wah Cantonment",
  "Sheikhupura",
  "Jhelum",
  "Gujrat",
  "Sahiwal",
  "Mirpur Khas",
  "Nawabshah",
  "Khairpur",
  "Jacobabad",
  "Chiniot",
  "Kamoke",
  "Khanewal",
  "Hafizabad",
  "Kohat",
  "Attock",
  "Muzaffargarh",
  "Mandi Bahauddin",
  "Vehari",
  "Dera Ismail Khan",
  "Bannu",
  "Swabi",
  "Charsadda",
  "Nowshera",
  "Haripur",
  "Pakpattan",
  "Toba Tek Singh",
  "Jhang",
  "Bhakkar",
  "Lodhran",
  "Narowal",
  "Shakargarh",
  "Murree",
  "Gilgit",
  "Skardu",
  "Muzaffarabad",
  "Mirpur",
  "Kotli",
  "Gwadar",
  "Turbat",
  "Khuzdar",
  "Sibi",
  "Zhob",
  "Chaman",
  "Hub",
  "Umerkot",
  "Ghotki",
  "Shikarpur",
  "Dadu",
  "Thatta",
  "Badin",
  "Kharian",
  "Wazirabad",
  "Arifwala",
  "Burewala",
  "Mianwali",
  "Chakwal"
] as const;

export type PakistanCity = (typeof pakistanCities)[number];
